kind: pipeline
type: docker
name: default

steps:
  - name: test_smpwebsrv
    image: golang:1.14
    commands:
      - cd pkg/smpwebsrv
      - go test
  - name: build_smpwebsrv
    image: golang:1.14
    commands:
      - cd cmd/smpwebsrv
      - go build
    depends_on:
      - test_smpwebsrv
  - name: docker_smpwebsrv
    image: plugins/docker
    settings:
      registry: github.com/hsmtkk/jissen_container
      repo: github.com/hsmtkk/jissen_container
      username: hsmtkk
      auth:
        from_secret: GIT_HUB_TOKEN
      dockerfile: build/smpwebsrv/Dockerfile
      tags: latest
    depends_on:
      - test_smpwebsrv
