kind: pipeline
type: docker
name: default

steps:
  - name: test_simple_web_server
    image: golang:1.14
    commands:
      - cd pkg/smpwebsrv
      - go test
  - name: build_simple_web_server
    image: golang:1.14
    commands:
      - cd cmd/smpwebsrv
      - go build
    depends_on:
      - test_simple_web_server
  - name: docker_simple_web_server
    image: plugins/docker
    settings:
      repo: hsmtkk/jissen_container
      username: hsmtkk
      auth:
        from_secret: GIT_HUB_TOKEN
      tags: latest
    depends_on:
      - test_simple_web_server
