kind: pipeline
type: docker
name: default

steps:
  - name: test_smpwebsrv
    image: golang:1.14
    commands:
      - cd pkg/smpwebsrv
      - go test
  - name: build_smpwebsrv
    image: golang:1.14
    commands:
      - cd cmd/smpwebsrv
      - go build
    depends_on:
      - test_smpwebsrv
  - name: docker_smpwebsrv
    image: plugins/docker
    settings:
      repo: docker.pkg.github.com/hsmtkk/jissen_container/smpwebsrv
      registry: github.com/hsmtkk/jissen_container
      username: hsmtkk
      password: 62d8db21379386e8ab4965d6438ee2163e39092b
      dockerfile: build/smpwebsrv/Dockerfile
      tags: latest
      debug: true
    depends_on:
      - test_smpwebsrv
