kind: pipeline
type: docker
name: default

steps:
  - name: test_smpwebsrv
    image: golang:1.14
    commands:
      - cd pkg/smpwebsrv
      - go test
  - name: build_smpwebsrv
    image: golang:1.14
    commands:
      - cd cmd/smpwebsrv
      - go build
    depends_on:
      - test_smpwebsrv
  - name: docker_smpwebsrv
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: GIT_HUB_TOKEN
      repo: docker.pkg.github.com/hsmtkk/jissen_container/smpwebsrv
      registry: docker.pkg.github.com
      dockerfile: build/smpwebsrv/Dockerfile
      tags: latest
    depends_on:
      - test_smpwebsrv
